CREATE TABLE IF NOT EXISTS UserRole (
    roleID VARCHAR(255) NOT NULL,
    userID VARCHAR(255) NOT NULL,
    FOREIGN KEY (roleID) REFERENCES Role(roleID),
    FOREIGN KEY (userID) REFERENCES User(userID)
);